FROM oddrationale/docker-shadowsocks

LABEL maintainer="zyxuan97@foxmail.com"

ARG APP=xv_3.5.0.33-1_amd64.deb

WORKDIR /VPN

COPY files /VPN
COPY install /VPN

# 切换国内源
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak \
  && cp /VPN/sources.list /etc/apt/sources.list
  
# 安装必要工具
RUN apt-get update && apt-get install -y inetutils-ping \
    net-tools cron git

# 升级 Shadowsocks 为最新版本
RUN pip install git+https://github.com/shadowsocks/shadowsocks.git@master

# 安装 ExpressVPN
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates wget expect iproute2 curl vim \
    && rm -rf /var/lib/apt/lists/* \
    && dpkg -i /VPN/${APP} \
    && apt-get purge -y --auto-remove wget
    
# 配置shadowsocks服务
RUN cp /VPN/shadowsocks.service /etc/systemd/system/ \
  && chmod a-x /etc/systemd/system/shadowsocks.service \
  && systemctl enable shadowsocks
  
# 配置expressvpnConnect服务
RUN cp /VPN/expressvpnConnect.service /etc/systemd/system/ \
  && chmod a-x /etc/systemd/system/expressvpnConnect.service \
  && systemctl enable expressvpnConnect

# 配置定时任务
RUN mkdir -p /var/spool/cron/crontabs \
  && cp /VPN/crontab /var/spool/cron/crontabs/root \
  && chown -R root:crontab /var/spool/cron/crontabs/root \
  && touch /var/log/cron.log \
  && systemctl enable cron

ENTRYPOINT ["/sbin/init"]
