FROM centos:centos8

LABEL maintainer="Yasin Zhang"

RUN yum install -y git 

RUN yum install -y wget setup perl

RUN mkdir -p /software/install && cd /software/install \
    && wget https://npm.taobao.org/mirrors/node/v8.15.0/node-v8.15.0-linux-x64.tar.xz \
    && tar -xvf node-v8.15.0-linux-x64.tar.xz -C /software \
    && ln -s /software/node-v8.15.0-linux-x64/bin/node /usr/local/bin/node \
    && ln -s /software/node-v8.15.0-linux-x64/bin/npm /usr/local/bin/npm
  
RUN yum install -y vim net-tools

RUN yum install -y python2

CMD ["tail", "-f", "/dev/null"]
