FROM testbase:latest

LABEL maintainer="Yasin Zhang"

COPY install /software/install

# 安装 MAVEN & JDK
RUN cd /software/install \
    && tar -xvf apache-maven-3.6.3-bin.tar.gz -C /software \
    && ln -s /software/apache-maven-3.6.3/bin/mvn /usr/local/bin/mvn \
    && rpm -iv jdk-8u261-linux-x64.rpm

CMD ["tail", "-f", "/dev/null"]
