FROM javabase:latest

LABEL maintainer="Yasin Zhang"

ARG NACOS=nacos-server-1.3.1

RUN mkdir -p /software/install

COPY install /software/install

# 安装 nacos
RUN cd /software/install \
    && tar -zxvf ${NACOS}.tar.gz -C /software

CMD ["tail", "-f", "/dev/null"]
