FROM javabase:latest

LABEL maintainer="Yasin Zhang"

RUN mkdir -p /software/install

COPY install /software/install

# 安装 nacos
RUN cd /software/install \
    && tar -zxvf nacos-server-1.3.1.tar.gz -C /software

CMD ["tail", "-f", "/dev/null"]
